name: Backup GitHub Repos

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: 'shrly-se'
      S3_BUCKET: 'github-repo-backups'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/YOUR_AWS_ROLE_NAME
          aws-region: us-east-1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq zip

      - name: Run Backup Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash backup.sh
